<?php

declare(strict_types=1);

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    public const ROOT_PACKAGE_NAME = 'laravel/laravel';
    public const VERSIONS          = array (
  'classpreloader/classpreloader' => '3.2.0@4729e438e0ada350f91148e7d4bb9809342575ff',
  'clue/stream-filter' => 'v1.4.1@5a58cc30a8bd6a4eb8f856adf61dd3e013f53f71',
  'danielstjules/stringy' => '1.10.0@4749c205db47ee5b32e8d1adf6d9aff8db6caf3b',
  'dnoegel/php-xdg-base-dir' => '0.1@265b8593498b997dc2d31e75b89f053b5cc9621a',
  'doctrine/inflector' => '1.3.1@ec3a55242203ffa6a4b27c58176da97ff0a7aec1',
  'guzzlehttp/guzzle' => '6.5.2@43ece0e75098b7ecd8d13918293029e555a50f82',
  'guzzlehttp/promises' => 'v1.3.1@a59da6cf61d80060647ff4d3eb2c03a2bc694646',
  'guzzlehttp/psr7' => '1.6.1@239400de7a173fe9901b9ac7c06497751f00727a',
  'http-interop/http-factory-guzzle' => '1.0.0@34861658efb9899a6618cef03de46e2a52c80fc0',
  'intervention/image' => '2.5.1@abbf18d5ab8367f96b3205ca3c89fb2fa598c69e',
  'jakub-onderka/php-console-color' => 'v0.2@d5deaecff52a0d61ccb613bb3804088da0307191',
  'jakub-onderka/php-console-highlighter' => 'v0.3.2@7daa75df45242c8d5b75a22c00a201e7954e4fb5',
  'jean85/pretty-package-versions' => '1.2@75c7effcf3f77501d0e0caa75111aff4daa0dd48',
  'jeremeamia/superclosure' => '2.4.0@5707d5821b30b9a07acfb4d76949784aaa0e9ce9',
  'kylekatarnls/update-helper' => '1.2.0@5786fa188e0361b9adf9e8199d7280d1b2db165e',
  'laravel/framework' => 'v5.1.46@7f2f892e62163138121e8210b92b21394fda8d1c',
  'laravel/socialite' => 'v2.0.22@67154ff06a43169a2efa28d870344a3a61c36bee',
  'laravelcollective/html' => 'v5.1.11@99342cc22507cf8d7178bb390c215968183993bb',
  'league/flysystem' => '1.0.64@d13c43dbd4b791f815215959105a008515d1a2e0',
  'league/oauth1-client' => '1.7.0@fca5f160650cb74d23fc11aa570dd61f86dcf647',
  'monolog/monolog' => '1.25.3@fa82921994db851a8becaf3787a9e73c5976b6f1',
  'mtdowling/cron-expression' => 'v1.2.3@9be552eebcc1ceec9776378f7dcc085246cacca6',
  'nesbot/carbon' => '1.39.1@4be0c005164249208ce1b5ca633cd57bdd42ff33',
  'nikic/php-parser' => 'v2.1.1@4dd659edadffdc2143e4753df655d866dbfeedf0',
  'ocramius/package-versions' => '1.4.2@44af6f3a2e2e04f2af46bcb302ad9600cba41c7d',
  'paragonie/random_compat' => 'v1.4.3@9b3899e3c3ddde89016f576edb8c489708ad64cd',
  'php-http/client-common' => '2.1.0@a8b29678d61556f45d6236b1667db16d998ceec5',
  'php-http/discovery' => '1.7.4@82dbef649ccffd8e4f22e1953c3a5265992b83c0',
  'php-http/guzzle6-adapter' => 'v2.0.1@6074a4b1f4d5c21061b70bab3b8ad484282fe31f',
  'php-http/httplug' => '2.1.0@72d2b129a48f0490d55b7f89be0d6aa0597ffb06',
  'php-http/message' => '1.8.0@ce8f43ac1e294b54aabf5808515c3554a19c1e1c',
  'php-http/message-factory' => 'v1.0.2@a478cb11f66a6ac48d8954216cfed9aa06a501a1',
  'php-http/promise' => 'v1.0.0@dc494cdc9d7160b9a09bd5573272195242ce7980',
  'psr/http-client' => '1.0.0@496a823ef742b632934724bf769560c2a5c7c44e',
  'psr/http-factory' => '1.0.1@12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.1.2@446d54b4cb6bf489fc9d75f55843658e6f25d801',
  'psy/psysh' => 'v0.7.2@e64e10b20f8d229cac76399e1f3edddb57a0f280',
  'ralouphie/getallheaders' => '3.0.3@120b605dfeb996808c31b6477290a714d356e822',
  'sentry/sdk' => '2.1.0@18921af9c2777517ef9fb480845c22a98554d6af',
  'sentry/sentry' => '2.3.2@b3e71feb32f1787b66a3b4fdb8686972e9c7ba94',
  'sentry/sentry-laravel' => '1.7.0@72684758f15aae4562149460b70fea81e9a06a25',
  'swiftmailer/swiftmailer' => 'v5.4.12@181b89f18a90f8925ef805f950d47a7190e9b950',
  'symfony/console' => 'v2.7.51@574cb4cfaa01ba115fc2fc0c2355b2c5472a4804',
  'symfony/css-selector' => 'v2.8.52@7b1692e418d7ccac24c373528453bc90e42797de',
  'symfony/debug' => 'v2.7.51@4a7330f29b3d215f8bacf076689f9d1c3d568681',
  'symfony/dom-crawler' => 'v2.7.51@d905e1c5885735ee66af60c205429b9941f24752',
  'symfony/event-dispatcher' => 'v2.8.52@a77e974a5fecb4398833b0709210e3d5e334ffb0',
  'symfony/finder' => 'v2.7.51@34226a3aa279f1e356ad56181b91acfdc9a2525c',
  'symfony/http-foundation' => 'v2.7.51@b67e5cbd2bf837fb3681f2c4965826d6c6758532',
  'symfony/http-kernel' => 'v2.7.52@435064b3b143f79469206915137c21e88b56bfb9',
  'symfony/options-resolver' => 'v5.0.7@09dccfffd24b311df7f184aa80ee7b61ad61ed8d',
  'symfony/polyfill-ctype' => 'v1.14.0@fbdeaec0df06cf3d51c93de80c7eb76e271f5a38',
  'symfony/polyfill-mbstring' => 'v1.14.0@34094cfa9abe1f0f14f48f490772db7a775559f2',
  'symfony/polyfill-php56' => 'v1.14.0@16ec91cb06998b609501b55b7177b7d7c02badb3',
  'symfony/polyfill-util' => 'v1.14.0@ba3cfcea6d0192cae46c62041f61cbb704b526d3',
  'symfony/polyfill-uuid' => 'v1.15.0@2318f7f470a892867f3de602e403d006b1b9c9aa',
  'symfony/process' => 'v2.7.51@eda637e05670e2afeec3842dcd646dce94262f6b',
  'symfony/routing' => 'v2.7.51@33bd5882f201f9a3b7dd9640b95710b71304c4fb',
  'symfony/translation' => 'v2.7.51@1959c78c5a32539ef221b3e18a961a96d949118f',
  'symfony/var-dumper' => 'v2.7.51@6f9271e94369db05807b261fcfefe4cd1aafd390',
  'veritrans/veritrans-php' => '1.2.0@8bb9291ab6275c362feda38b7fb683627c4e0201',
  'vlucas/phpdotenv' => 'v1.1.1@0cac554ce06277e33ddf9f0b7ade4b8bbf2af3fa',
  'barryvdh/laravel-debugbar' => 'v2.4.3@d7c88f08131f6404cb714f3f6cf0642f6afa3903',
  'doctrine/instantiator' => '1.3.0@ae466f726242e637cebdd526a7d991b9433bacf1',
  'fzaninotto/faker' => 'v1.9.1@fc10d778e4b84d5bd315dad194661e091d307c6f',
  'hamcrest/hamcrest-php' => 'v1.2.2@b37020aa976fa52d3de9aa904aa2522dc518f79c',
  'maximebf/debugbar' => '1.13.1@afee79a236348e39a44cb837106b7c5b4897ac2a',
  'mockery/mockery' => '0.9.11@be9bf28d8e57d67883cba9fcadfcff8caab667f8',
  'phpdocumentor/reflection-common' => '2.0.0@63a995caa1ca9e5590304cd845c15ad6d482a62a',
  'phpdocumentor/reflection-docblock' => '5.1.0@cd72d394ca794d3466a3b2fc09d5a6c1dc86b47e',
  'phpdocumentor/type-resolver' => '1.1.0@7462d5f123dfc080dfdf26897032a6513644fc95',
  'phpspec/php-diff' => 'v1.0.2@30e103d19519fe678ae64a60d77884ef3d71b28a',
  'phpspec/phpspec' => '2.5.8@d8a153dcb52f929b448c0bf2cc19c7388951adb1',
  'phpspec/prophecy' => 'v1.10.2@b4400efc9d206e83138e2bb97ed7f5b14b831cd9',
  'phpunit/php-code-coverage' => '2.2.4@eabf68b476ac7d0f73793aada060f1c1a9bf8979',
  'phpunit/php-file-iterator' => '1.4.5@730b01bc3e867237eaac355e06a36b85dd93a8b4',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '1.4.12@1ce90ba27c42e4e44e6d8458241466380b51fa16',
  'phpunit/phpunit' => '4.8.36@46023de9a91eec7dfb06cc56cb4e260017298517',
  'phpunit/phpunit-mock-objects' => '2.3.8@ac8e7a3db35738d56ee9a76e78a4e03d97628983',
  'sebastian/comparator' => '1.2.4@2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
  'sebastian/diff' => '1.4.3@7f066a26a962dbe58ddea9f72a4e82874a3975a4',
  'sebastian/environment' => '1.3.8@be2c607e43ce4c89ecd60e75c6a85c126e754aea',
  'sebastian/exporter' => '1.2.2@42c4c2eec485ee3e159ec9884f95b431287edde4',
  'sebastian/global-state' => '1.1.1@bc37d50fea7d017d3d340f230811c9f1d7280af4',
  'sebastian/recursion-context' => '1.0.5@b19cc3298482a335a95f3016d2f8a6950f0fbcd7',
  'sebastian/version' => '1.0.6@58b3a85e7999757d6ad81c787a1fbf5ff6c628c6',
  'symfony/yaml' => 'v3.3.18@af615970e265543a26ee712c958404eb9b7ac93d',
  'webmozart/assert' => '1.7.0@aed98a490f9a8f78468232db345ab9cf606cf598',
  'laravel/laravel' => 'dev-master@5c1bc948d2f9c59830dfc1e51dca93c38e7cdbac',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException If a version cannot be located.
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }
}
