<?php

declare(strict_types=1);

namespace PackageVersions;

use OutOfBoundsException;

/**
 * This class is generated by composer/package-versions-deprecated, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 *
 * @deprecated in favor of the Composer\InstalledVersions class provided by Composer 2. Require composer-runtime-api:^2 to ensure it is present.
 */
final class Versions
{
    const ROOT_PACKAGE_NAME = 'laravel/laravel';
    /**
     * Array of all available composer packages.
     * Dont read this array from your calling code, but use the \PackageVersions\Versions::getVersion() method instead.
     *
     * @var array<string, string>
     * @internal
     */
    const VERSIONS          = array (
  'classpreloader/classpreloader' => '3.2.1@297db07cabece3946f4a98d23f11f90aa10e1797',
  'clue/stream-filter' => 'v1.4.1@5a58cc30a8bd6a4eb8f856adf61dd3e013f53f71',
  'composer/package-versions-deprecated' => '1.8.2@7a8001fe2c9befad9d001bf54ef0b4a17d950d0f',
  'danielstjules/stringy' => '1.10.0@4749c205db47ee5b32e8d1adf6d9aff8db6caf3b',
  'dnoegel/php-xdg-base-dir' => '0.1@265b8593498b997dc2d31e75b89f053b5cc9621a',
  'doctrine/inflector' => '1.4.3@4650c8b30c753a76bf44fb2ed00117d6f367490c',
  'guzzlehttp/guzzle' => '6.5.5@9d4290de1cfd701f38099ef7e183b64b4b7b0c5e',
  'guzzlehttp/promises' => 'v1.3.1@a59da6cf61d80060647ff4d3eb2c03a2bc694646',
  'guzzlehttp/psr7' => '1.6.1@239400de7a173fe9901b9ac7c06497751f00727a',
  'http-interop/http-factory-guzzle' => '1.0.0@34861658efb9899a6618cef03de46e2a52c80fc0',
  'intervention/image' => '2.5.1@abbf18d5ab8367f96b3205ca3c89fb2fa598c69e',
  'jakub-onderka/php-console-color' => 'v0.2@d5deaecff52a0d61ccb613bb3804088da0307191',
  'jakub-onderka/php-console-highlighter' => 'v0.3.2@7daa75df45242c8d5b75a22c00a201e7954e4fb5',
  'jean85/pretty-package-versions' => '1.5.0@e9f4324e88b8664be386d90cf60fbc202e1f7fc9',
  'jeremeamia/superclosure' => '2.4.0@5707d5821b30b9a07acfb4d76949784aaa0e9ce9',
  'kylekatarnls/update-helper' => '1.2.1@429be50660ed8a196e0798e5939760f168ec8ce9',
  'laravel/framework' => 'v5.1.46@7f2f892e62163138121e8210b92b21394fda8d1c',
  'laravel/socialite' => 'v2.0.22@67154ff06a43169a2efa28d870344a3a61c36bee',
  'laravelcollective/html' => 'v5.1.11@99342cc22507cf8d7178bb390c215968183993bb',
  'league/flysystem' => '1.0.69@7106f78428a344bc4f643c233a94e48795f10967',
  'league/fractal' => '0.19.2@06dc15f6ba38f2dde2f919d3095d13b571190a7c',
  'league/oauth1-client' => '1.7.0@fca5f160650cb74d23fc11aa570dd61f86dcf647',
  'maatwebsite/excel' => '2.1.30@f5540c4ba3ac50cebd98b09ca42e61f926ef299f',
  'monolog/monolog' => '1.25.4@3022efff205e2448b560c833c6fbbf91c3139168',
  'mtdowling/cron-expression' => 'v1.2.3@9be552eebcc1ceec9776378f7dcc085246cacca6',
  'nesbot/carbon' => '1.39.1@4be0c005164249208ce1b5ca633cd57bdd42ff33',
  'nikic/php-parser' => 'v2.1.1@4dd659edadffdc2143e4753df655d866dbfeedf0',
  'paragonie/random_compat' => 'v1.4.3@9b3899e3c3ddde89016f576edb8c489708ad64cd',
  'php-http/client-common' => '2.2.1@d70de2f7bf575ef19350b8aab504857943ab2922',
  'php-http/discovery' => '1.9.1@64a18cc891957e05d91910b3c717d6bd11fbede9',
  'php-http/guzzle6-adapter' => 'v2.0.1@6074a4b1f4d5c21061b70bab3b8ad484282fe31f',
  'php-http/httplug' => '2.2.0@191a0a1b41ed026b717421931f8d3bd2514ffbf9',
  'php-http/message' => '1.8.0@ce8f43ac1e294b54aabf5808515c3554a19c1e1c',
  'php-http/message-factory' => 'v1.0.2@a478cb11f66a6ac48d8954216cfed9aa06a501a1',
  'php-http/promise' => '1.1.0@4c4c1f9b7289a2ec57cde7f1e9762a5789506f88',
  'phpoffice/phpexcel' => '1.8.2@1441011fb7ecdd8cc689878f54f8b58a6805f870',
  'psr/http-client' => '1.0.1@2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
  'psr/http-factory' => '1.0.1@12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.1.3@0f73288fd15629204f9d42b7055f72dacbe811fc',
  'psy/psysh' => 'v0.7.2@e64e10b20f8d229cac76399e1f3edddb57a0f280',
  'ralouphie/getallheaders' => '3.0.3@120b605dfeb996808c31b6477290a714d356e822',
  'sentry/sdk' => '2.1.0@18921af9c2777517ef9fb480845c22a98554d6af',
  'sentry/sentry' => '2.4.1@407573e22e6cc46b72cff07c117eeb16bf3a17de',
  'sentry/sentry-laravel' => '1.7.0@72684758f15aae4562149460b70fea81e9a06a25',
  'swiftmailer/swiftmailer' => 'v5.4.12@181b89f18a90f8925ef805f950d47a7190e9b950',
  'symfony/console' => 'v2.7.51@574cb4cfaa01ba115fc2fc0c2355b2c5472a4804',
  'symfony/css-selector' => 'v2.8.52@7b1692e418d7ccac24c373528453bc90e42797de',
  'symfony/debug' => 'v2.7.51@4a7330f29b3d215f8bacf076689f9d1c3d568681',
  'symfony/deprecation-contracts' => 'v2.1.3@5e20b83385a77593259c9f8beb2c43cd03b2ac14',
  'symfony/dom-crawler' => 'v2.7.51@d905e1c5885735ee66af60c205429b9941f24752',
  'symfony/event-dispatcher' => 'v2.8.52@a77e974a5fecb4398833b0709210e3d5e334ffb0',
  'symfony/finder' => 'v2.7.51@34226a3aa279f1e356ad56181b91acfdc9a2525c',
  'symfony/http-foundation' => 'v2.7.51@b67e5cbd2bf837fb3681f2c4965826d6c6758532',
  'symfony/http-kernel' => 'v2.7.52@435064b3b143f79469206915137c21e88b56bfb9',
  'symfony/options-resolver' => 'v5.1.2@663f5dd5e14057d1954fe721f9709d35837f2447',
  'symfony/polyfill-ctype' => 'v1.17.1@2edd75b8b35d62fd3eeabba73b26b8f1f60ce13d',
  'symfony/polyfill-intl-idn' => 'v1.17.1@a57f8161502549a742a63c09f0a604997bf47027',
  'symfony/polyfill-mbstring' => 'v1.17.1@7110338d81ce1cbc3e273136e4574663627037a7',
  'symfony/polyfill-php56' => 'v1.17.1@a25861bb3c79b0ec2da9ede51de2ea573818b943',
  'symfony/polyfill-php72' => 'v1.17.0@f048e612a3905f34931127360bdd2def19a5e582',
  'symfony/polyfill-php80' => 'v1.17.1@4a5b6bba3259902e386eb80dd1956181ee90b5b2',
  'symfony/polyfill-util' => 'v1.17.1@6dd644eda43cd2f3daa883d728d8ab4120a05af6',
  'symfony/polyfill-uuid' => 'v1.17.1@5db3e66818f1f768b585220438436ea6c1e0b874',
  'symfony/process' => 'v2.7.51@eda637e05670e2afeec3842dcd646dce94262f6b',
  'symfony/routing' => 'v2.7.51@33bd5882f201f9a3b7dd9640b95710b71304c4fb',
  'symfony/translation' => 'v2.7.51@1959c78c5a32539ef221b3e18a961a96d949118f',
  'symfony/var-dumper' => 'v2.7.51@6f9271e94369db05807b261fcfefe4cd1aafd390',
  'tijsverkoyen/css-to-inline-styles' => '2.2.3@b43b05cf43c1b6d849478965062b6ef73e223bb5',
  'veritrans/veritrans-php' => '1.2.0@8bb9291ab6275c362feda38b7fb683627c4e0201',
  'vlucas/phpdotenv' => 'v1.1.1@0cac554ce06277e33ddf9f0b7ade4b8bbf2af3fa',
  'yajra/laravel-datatables-oracle' => 'v5.12.5@4cc8d86de795af03c5f320711a9645b8a295b95f',
  'barryvdh/laravel-debugbar' => 'v2.4.3@d7c88f08131f6404cb714f3f6cf0642f6afa3903',
  'doctrine/instantiator' => '1.3.1@f350df0268e904597e3bd9c4685c53e0e333feea',
  'fzaninotto/faker' => 'v1.9.1@fc10d778e4b84d5bd315dad194661e091d307c6f',
  'hamcrest/hamcrest-php' => 'v1.2.2@b37020aa976fa52d3de9aa904aa2522dc518f79c',
  'maximebf/debugbar' => '1.13.1@afee79a236348e39a44cb837106b7c5b4897ac2a',
  'mockery/mockery' => '0.9.11@be9bf28d8e57d67883cba9fcadfcff8caab667f8',
  'phpdocumentor/reflection-common' => '2.2.0@1d01c49d4ed62f25aa84a747ad35d5a16924662b',
  'phpdocumentor/reflection-docblock' => '5.1.0@cd72d394ca794d3466a3b2fc09d5a6c1dc86b47e',
  'phpdocumentor/type-resolver' => '1.3.0@e878a14a65245fbe78f8080eba03b47c3b705651',
  'phpspec/php-diff' => 'v1.0.2@30e103d19519fe678ae64a60d77884ef3d71b28a',
  'phpspec/phpspec' => '2.5.8@d8a153dcb52f929b448c0bf2cc19c7388951adb1',
  'phpspec/prophecy' => 'v1.10.3@451c3cd1418cf640de218914901e51b064abb093',
  'phpunit/php-code-coverage' => '2.2.4@eabf68b476ac7d0f73793aada060f1c1a9bf8979',
  'phpunit/php-file-iterator' => '1.4.5@730b01bc3e867237eaac355e06a36b85dd93a8b4',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '1.4.12@1ce90ba27c42e4e44e6d8458241466380b51fa16',
  'phpunit/phpunit' => '4.8.36@46023de9a91eec7dfb06cc56cb4e260017298517',
  'phpunit/phpunit-mock-objects' => '2.3.8@ac8e7a3db35738d56ee9a76e78a4e03d97628983',
  'sebastian/comparator' => '1.2.4@2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
  'sebastian/diff' => '1.4.3@7f066a26a962dbe58ddea9f72a4e82874a3975a4',
  'sebastian/environment' => '1.3.8@be2c607e43ce4c89ecd60e75c6a85c126e754aea',
  'sebastian/exporter' => '1.2.2@42c4c2eec485ee3e159ec9884f95b431287edde4',
  'sebastian/global-state' => '1.1.1@bc37d50fea7d017d3d340f230811c9f1d7280af4',
  'sebastian/recursion-context' => '1.0.5@b19cc3298482a335a95f3016d2f8a6950f0fbcd7',
  'sebastian/version' => '1.0.6@58b3a85e7999757d6ad81c787a1fbf5ff6c628c6',
  'symfony/yaml' => 'v3.3.18@af615970e265543a26ee712c958404eb9b7ac93d',
  'webmozart/assert' => '1.9.1@bafc69caeb4d49c39fd0779086c03a3738cbb389',
  'laravel/laravel' => 'dev-master@9f7d2d411fca5c17ac9448a9623214bc6534a156',
);

    private function __construct()
    {
    }

    /**
     * @throws OutOfBoundsException If a version cannot be located.
     *
     * @psalm-param key-of<self::VERSIONS> $packageName
     * @psalm-pure
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }
}
