<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'yajra\\Datatables' => array($vendorDir . '/yajra/laravel-datatables-oracle/src'),
    'UpdateHelper\\' => array($vendorDir . '/kylekatarnls/update-helper/src'),
    'Sentry\\Laravel\\' => array($vendorDir . '/sentry/sentry-laravel/src'),
    'PhpSpec' => array($vendorDir . '/phpspec/phpspec/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Maatwebsite\\Excel\\' => array($vendorDir . '/maatwebsite/excel/src'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'Dotenv' => array($vendorDir . '/vlucas/phpdotenv/src'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
);
